# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/controller@sha256:675aebfd596f8250293facc686a270dc579960c7ffc439ade38997b7b5432fcb
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/controller@sha256:675aebfd596f8250293facc686a270dc579960c7ffc439ade38997b7b5432fcb jaywinz/gcr.io.knative-releases.knative.dev.eventing.cmd.controller:v1.0.1
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/mtping@sha256:574e56b00623d53824e942e6e4fb68a0e3ca71a59a18065f31381a235c4e549a
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/mtping@sha256:574e56b00623d53824e942e6e4fb68a0e3ca71a59a18065f31381a235c4e549a jaywinz/gcr.io.knative-releases.knative.dev.eventing.cmd.mtping:v1.0.1
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/webhook@sha256:6edf3f4242f5168acae422e4b20a2fd385e4dc7b328f17f54bdbeaae2c05d4a8
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/webhook@sha256:6edf3f4242f5168acae422e4b20a2fd385e4dc7b328f17f54bdbeaae2c05d4a8 jaywinz/gcr.io.knative-releases.knative.dev.eventing.cmd.webhook:v1.0.1
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_controller@sha256:f317a2ab47b68770019de8a97c7bb011db584d0c8c50a903e5166d384bf8bcf4
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_controller@sha256:f317a2ab47b68770019de8a97c7bb011db584d0c8c50a903e5166d384bf8bcf4 jaywinz/gcr.io.knative-releases.knative.dev.eventing.cmd.in_memory.channel_controller:v1.0.1
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_dispatcher@sha256:5060df205de33a5f7da15e6beeb90ab8d966ea425f3100a1b36761125a26aab4
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_dispatcher@sha256:5060df205de33a5f7da15e6beeb90ab8d966ea425f3100a1b36761125a26aab4 jaywinz/gcr.io.knative-releases.knative.dev.eventing.cmd.in_memory.channel_dispatcher:v1.0.1
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/broker/filter@sha256:102f2804a1c7a13c4d8f870162cdf430283b85d2cd15389da3fe9a32209fb1a5
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/broker/filter@sha256:102f2804a1c7a13c4d8f870162cdf430283b85d2cd15389da3fe9a32209fb1a5 jaywinz/gcr.io.knative-releases.knative.dev.eventing.cmd.broker.filter:v1.0.1
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/broker/ingress@sha256:05affdaae77c81d3da1b96041b81c90face2f22b36096b61655e80d8383dcc26
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/broker/ingress@sha256:05affdaae77c81d3da1b96041b81c90face2f22b36096b61655e80d8383dcc26 jaywinz/gcr.io.knative-releases.knative.dev.eventing.cmd.broker.ingress:v1.0.1
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/mtchannel_broker@sha256:24e9d6576947b29922a19c7621eff40402c79fcf2c58446227df92597934192a
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/mtchannel_broker@sha256:24e9d6576947b29922a19c7621eff40402c79fcf2c58446227df92597934192a jaywinz/gcr.io.knative-releases.knative.dev.eventing.cmd.mtchannel_broker:v1.0.1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Runs a set of commands using the runners shell
      - name: Push to Docker Registry
        run: |
          docker push jaywinz/gcr.io.knative-releases.knative.dev.eventing.cmd.mtping:v1.0.1
          docker push jaywinz/gcr.io.knative-releases.knative.dev.eventing.cmd.controller:v1.0.1
          docker push jaywinz/gcr.io.knative-releases.knative.dev.eventing.cmd.webhook:v1.0.1
          docker push jaywinz/gcr.io.knative-releases.knative.dev.eventing.cmd.in_memory.channel_controller:v1.0.1
          docker push jaywinz/gcr.io.knative-releases.knative.dev.eventing.cmd.in_memory.channel_dispatcher:v1.0.1
          docker push jaywinz/gcr.io.knative-releases.knative.dev.eventing.cmd.broker.filter:v1.0.1
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/broker/ingress@sha256:05affdaae77c81d3da1b96041b81c90face2f22b36096b61655e80d8383dcc26
          docker push jaywinz/gcr.io.knative-releases.knative.dev.eventing.cmd.broker.ingress:v1.0.1
          docker push jaywinz/gcr.io.knative-releases.knative.dev.eventing.cmd.mtchannel_broker:v1.0.1


