# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          docker pull gcr.io/knative-releases/knative.dev/eventing-gitlab/cmd/receive_adapter@sha256:e2d6280f63b345c30d69d06fc72767275a531eae72f38ad5da4322e20fc996f2
          docker tag gcr.io/knative-releases/knative.dev/eventing-gitlab/cmd/receive_adapter@sha256:e2d6280f63b345c30d69d06fc72767275a531eae72f38ad5da4322e20fc996f2 jaywinz/gcr.io.knative-releases.knative.dev.eventing-gitlab.cmd.receive_adapter:v1.0.1
          docker pull gcr.io/knative-releases/knative.dev/eventing-gitlab/cmd/controller@sha256:3010ab7cc279bd223c874f756d4e95ab28d5df7cde31dee3dbeab08af60422c9
          docker tag gcr.io/knative-releases/knative.dev/eventing-gitlab/cmd/controller@sha256:3010ab7cc279bd223c874f756d4e95ab28d5df7cde31dee3dbeab08af60422c9 jaywinz/gcr.io.knative-releases.knative.dev.eventing-gitlab.cmd.controller:v1.0.1
          docker pull gcr.io/knative-releases/knative.dev/eventing-gitlab/cmd/webhook@sha256:55e8bdbe4a5105d41cd2f5b83a046d5bc820948f9d84f76aef1c1076768338c3
          docker tag gcr.io/knative-releases/knative.dev/eventing-gitlab/cmd/webhook@sha256:55e8bdbe4a5105d41cd2f5b83a046d5bc820948f9d84f76aef1c1076768338c3 jaywinz/gcr.io.knative-releases.knative.dev.eventing-gitlab.cmd.webhook:v1.0.1

          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Runs a set of commands using the runners shell
      - name: Push to Docker Registry
        run: |
          docker push jaywinz/gcr.io.knative-releases.knative.dev.eventing-gitlab.cmd.webhook:v1.0.1
          docker push jaywinz/gcr.io.knative-releases.knative.dev.eventing-gitlab.cmd.controller:v1.0.1
          docker push jaywinz/gcr.io.knative-releases.knative.dev.eventing-gitlab.cmd.webhook:v1.0.1

          


